DROP TABLE IF EXISTS plant_fertilizer;
DROP TABLE IF EXISTS fertilizer;
DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS plant;

CREATE TABLE plant (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       type VARCHAR(50) NOT NULL,
                       planting_date DATE,
                       health_status VARCHAR(50),
                       is_annual BOOLEAN,
                       description VARCHAR(255),
                       height INTEGER,
                       version INTEGER,
                       created_at TIMESTAMP,
                       updated_at TIMESTAMP
);

CREATE TABLE task (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      created_at TIMESTAMP,
                      notes VARCHAR(255),
                      status VARCHAR(255),
                      task_date DATE,
                      task_type VARCHAR(255),
                      updated_at TIMESTAMP,
                      version INTEGER,
                      plant_id BIGINT,
                      CONSTRAINT fk_plant FOREIGN KEY (plant_id) REFERENCES plant(id)
);

CREATE TABLE fertilizer (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            application_method VARCHAR(255),
                            created_at TIMESTAMP,
                            name VARCHAR(255),
                            type VARCHAR(255),
                            updated_at TIMESTAMP,
                            usage_recommendations VARCHAR(255),
                            version INTEGER
);

CREATE TABLE plant_fertilizer (
                                  plant_id BIGINT NOT NULL,
                                  fertilizer_id BIGINT NOT NULL,
                                  CONSTRAINT pk_plant_fertilizer PRIMARY KEY (plant_id, fertilizer_id),
                                  CONSTRAINT fk_pf_plant FOREIGN KEY (plant_id) REFERENCES plant(id) ON DELETE CASCADE,
                                  CONSTRAINT fk_pf_fertilizer FOREIGN KEY (fertilizer_id) REFERENCES fertilizer(id) ON DELETE CASCADE
);

INSERT INTO plant (name, type, planting_date, health_status, is_annual, description, height, version, created_at, updated_at)
VALUES ('Tulip', 'FLOWER', '2024-03-01', 'HEALTHY', true, 'Test', 25, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO task (task_type, notes, task_date, status, plant_id, version, created_at, updated_at)
VALUES ('WATERING', 'Water me', '2025-03-01', 'OVERDUE', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);